Phương pháp lặp đơn

In [17]:
import numpy as np
import pandas as pd

pd.set_option('display.precision', 15)  # Increase decimal precision
pd.set_option('display.width', 150)     # Wider display
pd.set_option('display.max_columns', None)  # Show all column

In [18]:
def read_matrix_from_file(filename):
    """
    Read a matrix from a text file and display it.
    
    Parameters:
    filename (str): Path to the text file containing the matrix
    
    Returns:
    numpy.ndarray: The matrix read from the file
    """
    try:
        # Read the matrix from the file
        matrix = np.loadtxt(filename)
        
        # Display the matrix
        print("Matrix read from file:")
        print(matrix)
        
        return matrix
    
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
        return None
    except Exception as e:
        print(f"Error reading file: {str(e)}")
        return None

In [19]:
B = read_matrix_from_file('FXP_input_A.txt')
d = read_matrix_from_file('FXP_input_B.txt')

Matrix read from file:
[[0.1588 0.0064 0.0025 0.0304 0.0014 0.0083 0.1594]
 [0.0057 0.2645 0.0436 0.0099 0.0083 0.0201 0.3413]
 [0.0264 0.1506 0.3557 0.0139 0.0142 0.007  0.0236]
 [0.3299 0.0565 0.0495 0.3636 0.0204 0.0483 0.0649]
 [0.0089 0.0081 0.0333 0.0295 0.3412 0.0237 0.002 ]
 [0.119  0.0901 0.0996 0.126  0.1722 0.2368 0.3369]
 [0.0063 0.0126 0.0196 0.0098 0.0064 0.0132 0.0012]]
Matrix read from file:
[ 74000.  56000.  10500.  25000.  17500. 196000.   5000.]


In [20]:
def fixed_point_matrix_iteration(A, B, initial_values, q, eps, norm=1):
    """
    Perform fixed-point iteration for system of linear equations using x_new = Ax + B
    
    Parameters:
    A (numpy.ndarray): Coefficient matrix
    B (numpy.ndarray): Constant vector
    initial_values (numpy.ndarray): Initial guess for x
    q (float): Contraction coefficient
    eps (float): Tolerance for convergence
    norm (int): Type of norm to use (1 for L1 norm, -1 for max norm)
    
    Returns:
    numpy.ndarray: Solution vector
    """
    n = len(initial_values)
    values = np.array(initial_values)
    results = [[0] + initial_values.tolist()]
    i = 0

    new_eps = eps * (1-q) / q
    print(f"new_eps: {new_eps}")

    while True:
        # Calculate new values using matrix operation x_new = Ax + B
        new_values = np.dot(A, values) + B
        
        # Calculate the differences
        diffs = np.abs(new_values - values)
        if norm == 1:
            total_diff = np.sum(diffs)
        elif norm == -1:
            total_diff = np.max(diffs)
        
        # Append results
        results.append([i+1] + new_values.tolist() + diffs.tolist() + [total_diff])
        values = new_values
        
        # Check for convergence
        if total_diff < new_eps:
            break
        i += 1
        
    columns = ['Iteration'] + [f'x{j+1}' for j in range(n)] + [f'diff_x{j+1}' for j in range(n)] + ['total_diff']
    df = pd.DataFrame(results, columns=columns)
    print(df.to_string(index=False))
    
    return values

In [21]:
# Example usage
A = read_matrix_from_file('FXP_input_A.txt')
B = read_matrix_from_file('FXP_input_B.txt')

# Initial guess (zero vector or any other initial guess)
initial_guess = np.zeros(len(B))

# Call the function
solution = fixed_point_matrix_iteration(A, B, initial_guess, q=np.linalg.norm(A, ord=1), eps=10, norm=1)
print("Approximate solution:", solution)

Matrix read from file:
[[0.1588 0.0064 0.0025 0.0304 0.0014 0.0083 0.1594]
 [0.0057 0.2645 0.0436 0.0099 0.0083 0.0201 0.3413]
 [0.0264 0.1506 0.3557 0.0139 0.0142 0.007  0.0236]
 [0.3299 0.0565 0.0495 0.3636 0.0204 0.0483 0.0649]
 [0.0089 0.0081 0.0333 0.0295 0.3412 0.0237 0.002 ]
 [0.119  0.0901 0.0996 0.126  0.1722 0.2368 0.3369]
 [0.0063 0.0126 0.0196 0.0098 0.0064 0.0132 0.0012]]
Matrix read from file:
[ 74000.  56000.  10500.  25000.  17500. 196000.   5000.]
new_eps: 0.7607876896588854
 Iteration                    x1                    x2                    x3                     x4                    x5                     x6                    x7               diff_x1               diff_x2               diff_x3               diff_x4               diff_x5                diff_x6              diff_x7             total_diff
         0     0.000000000000000     0.000000000000000     0.000000000000000      0.000000000000000     0.000000000000000      0.000000000000000     0.00000000