Phân tách LU


In [40]:
import numpy as np

def read_matrix_from_file(filename):
    """
    Read a matrix from a text file and display it.
    
    Parameters:
    filename (str): Path to the text file containing the matrix
    
    Returns:
    numpy.ndarray: The matrix read from the file
    """
    try:
        # Read the matrix from the file
        matrix = np.loadtxt(filename)
        
        # Display the matrix
        print("Matrix read from file:")
        print(matrix, "\n")
        
        return matrix
    
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
        return None
    except Exception as e:
        print(f"Error reading file: {str(e)}")
        return None

In [41]:
def lu_decomposition(A):
    """
    Perform LU decomposition on matrix A with U having unit diagonal.
    
    Parameters:
    A (numpy.ndarray): Input square matrix
    
    Returns:
    tuple: (L, U) matrices where U has diagonal elements = 1
    """
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))
    
    # Set diagonal of U to 1
    np.fill_diagonal(U, 1)
    
    # LU decomposition
    for i in range(n):
        # Lower triangular matrix
        L[i][i] = A[i][i] - sum(L[i][j] * U[j][i] for j in range(i))
        
        for k in range(i + 1, n):
            # Lower triangular elements
            L[k][i] = A[k][i] - sum(L[k][j] * U[j][i] for j in range(i))
            
            # Upper triangular elements (normalized)
            U[i][k] = (A[i][k] - sum(L[i][j] * U[j][k] for j in range(i))) / L[i][i]

        print(f"Step {i + 1}:")
        print("L:", L, "\n", "U:", U, "\n")
    
    return L, U

In [42]:
def verify_lu_decomposition(A, L, U):
    """
    Verify LU decomposition by multiplying L and U and comparing with original matrix.
    
    Parameters:
    A (numpy.ndarray): Original matrix
    L (numpy.ndarray): Lower triangular matrix
    U (numpy.ndarray): Upper triangular matrix
    """
    print("\nLower triangular matrix L:")
    print(L)
    print("\nUpper triangular matrix U:")
    print(U)
    
    # Multiply L and U
    LU = np.dot(L, U)
    print("\nL × U:")
    print(LU)
    
    # Check if LU equals A
    if np.allclose(LU, A):
        print("\nVerification successful: LU = A")
    else:
        print("\nVerification failed: LU ≠ A")

In [44]:
# Example usage
A = read_matrix_from_file('LU_input_A.txt')
if A is not None:
    L, U = lu_decomposition(A)
    verify_lu_decomposition(A, L, U)

Matrix read from file:
[[ 2.  3. -5.]
 [ 1.  4.  2.]
 [ 3.  7.  1.]] 

Step 1:
L: [[2. 0. 0.]
 [1. 0. 0.]
 [3. 0. 0.]] 
 U: [[ 1.   1.5 -2.5]
 [ 0.   1.   0. ]
 [ 0.   0.   1. ]] 

Step 2:
L: [[2.  0.  0. ]
 [1.  2.5 0. ]
 [3.  2.5 0. ]] 
 U: [[ 1.   1.5 -2.5]
 [ 0.   1.   1.8]
 [ 0.   0.   1. ]] 

Step 3:
L: [[2.  0.  0. ]
 [1.  2.5 0. ]
 [3.  2.5 4. ]] 
 U: [[ 1.   1.5 -2.5]
 [ 0.   1.   1.8]
 [ 0.   0.   1. ]] 


Lower triangular matrix L:
[[2.  0.  0. ]
 [1.  2.5 0. ]
 [3.  2.5 4. ]]

Upper triangular matrix U:
[[ 1.   1.5 -2.5]
 [ 0.   1.   1.8]
 [ 0.   0.   1. ]]

L × U:
[[ 2.  3. -5.]
 [ 1.  4.  2.]
 [ 3.  7.  1.]]

Verification successful: LU = A
